name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Match your Node.js version

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Match your Node.js version

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-cqudjv0gph6c739vlpq0?key=YXilnP49yfQ \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

      - name: Deploy to Render (Frontend)
        run: |
          curl -X POST https://api.render.com/deploy/srv-cqudkfggph6c739vm2f0?key=-Kp-p1lmYPE \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
